language: python
before_script:
  - pip install tox codecov

script: tox

matrix:
  include:
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: pypy
      env: TOXENV=pypy
    - python: 3.6
      env: TOXENV=lint
           BLACK_ARGS='--check'
    - python: 3.7
      env: TOXENV=docs

notifications:
  on_success: change
  on_failure: always

after_success:
  - codecov
